### ISSUE TITLE
TestDetectionProperties test case failing due to wrong keyword argument

### ISSUE THREAD

**Issue by olaoluwa-98** [audreyr/binaryornot#46]
`average_size` is used in the `given` decorator on `test_never_crashes` method. The keyword argument doesn't exist on `hypothesis's given` method instead it's `min_size=0` and  `max_size=None`. The `TestDetectionProperties` test case is failing due to this.
```
ImportError: Failed to import test module: tests.test_check
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/olaoluwa-98/Desktop/software-dev/opensource/binaryornot/tests/test_check.py", line 218, in <module>
    class TestDetectionProperties(unittest.TestCase):
  File "/home/olaoluwa-98/Desktop/software-dev/opensource/binaryornot/tests/test_check.py", line 220, in TestDetectionProperties
    @given(binary(average_size=512))
TypeError: binary() got an unexpected keyword argument 'average_size'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by olaoluwa-98** [comment]
#42 fixes this

**Comment by olaoluwa-98** [comment]
#52 fixes this also and has been merged

**Comment by dvzrv** [comment]
@audreyr Could you please tag a release with this fix included?

I'm currently packaging python-binaryornot for Arch Linux and would like to not have to apply two patches to test this package if possible.
